### ISSUE TITLE
Takes very long to start

### ISSUE THREAD

**Issue by phihag** [ianbytchek/docker-riak-cs#13]
I'm looking to simulate S3 locally. On debian stretch amd64 (a Thinkpad X1 Gen 6 Carbon), it takes about 98s from typing
```
docker run -p 127.0.0.1:1234:8080  ianbytchek/riak-cs
```

till the final output
```
2018-09-10 11:37:15,595 INFO success: riak-cs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Until that final output, riak is not usable, and the CPU load is 100%.

In contrast, competing projects take about 0.1s to start.

If there is any compilation needed, it should be done as part of the build process, not during spin-up of the container.

**Comment by iby** [comment]
This is a low-maintenance repo and was created due to lack of adequate solutions back at the time. Riak was one of the few options with S3 compatibility, it's a super-heavy and fairly complex setup with loading time being just the tip of the iceberg. If you have an alternative solution – just stick with it.
