### ISSUE TITLE
Volumes for s3 data

### ISSUE THREAD

**Issue by lksv** [ianbytchek/docker-riak-cs#6]
Firstly, thank you for perfect docker image.

I would like to store bigger data and make them persistent (docker service restart / server restart).
I guess that I can set custom `--volume` param, but unfortunately I do not know which directory I have to mount.

**UPDATE**
I can change storage by `-v /my/storage:/var/lib/riak` but unfortunately (and obviously) it doesn't work - this corrupt/clear the riak DB internal storage. Is it possible to fix it somehow?

**Comment by iby** [comment]
My pleasure. Regarding the volumes – this is something I wanted to do myself for awhile, but been occasionally hitting [this](https://github.com/Parallels/docker-machine-parallels/issues/12) issue, which seemed like a show stopper.

Just tried doing what you did without much success either. The biggest bet was on copying `/var/lib/riak` from fresh container to host and then mounting that as a volume after. That didn't work, probably due to file permissions, but I haven't figured this out yet. I'll look further into this tonight.

**Comment by iby** [comment]
It looks like there might be a problem with LevelDB. As far as I understood everything must just work with empty `/var/lib/riak` folder, given it has the right permissions and ownership. But… I'm always getting `IO error: /var/lib/riak/cluster_meta/trees/MANIFEST-000001: Invalid argument`, which also described in https://github.com/Level/levelup/issues/222.

Some comments state that a workaround is to use NFS mounts over standard shared folders. You can easily give that a go with [adlogix/docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs). One piece of advice – test it with another vm first, I had great issues with it at first because of my firewall.

I will update the built image in the next hour to ensure the right permissions are set on the data dirs in entrypoint. Let me know if you how if it worked.

**Comment by lksv** [comment]
I use linux and yours linked issues are probably (docker-non-native-platforms) related. I do not prefer nfs to be involved (at least on linux).

I am already able to run riak with monted folder, but I need to set `chmod a+rwx $MOUNTED_HOST_FOLDER`. Then I can start docker container by: `sudo docker run -dP -e 'RIAK_CS_BUCKETS=foo,bar,baz' --name 'riak-cs' -p '8080:8080' -v $MOUNTED_HOST_FOLDER:/var/lib/riak ianbytchek/riak-cs`. Which means that ensuring right permissions in for `/var/lib/riak` folder in `configure_application.sh` script helps.

There is one more issue. When I start the docker container again and see `docker logs` I get:

```
Starting Riak… OK!
Starting Stanchion… OK!
Starting Riak CS… OK!
Could not create admin user and retrieve credentiels…
```

Is this problem of early timeout?

Btw, how do you debug the image? Becase of `entrypoint.sh` has only `if [ "$1" = 'riak' ]; then` branch, I cannot start docker container with `-i -t ianbytchek/riak-cs /bin/bash`.

**Comment by iby** [comment]
Good to know that it actually works. With regards to `Could not create admin user and retrieve credentials…`. There was an issue with timeouts that was fixed with `--connect-timeout 5 --retry 10 --retry-delay 5` on curl. I added more information to output when credentials setup fails, run it again and post what it outputs.

Debugging part wasn't very obvious, you'd have to overwrite entrypoint and run it with `… --entrypoint bash ianbytchek/riak-cs -s`. I just updated the image (make sure to pull the latest), making this as easy as just passing `bash` command:

``` sh
docker -ti ianbytchek/riak-cs bash
```

The best way to debug is to clone the repo and mount `/src/script/configure_application.sh:/entrypoint/script/configure_application.sh` or any other file in that manner. Files that go into `/entrypoint` can be found in `/src/script/build.sh`. Then you launch the container and see what happens, update the `configure_application.sh` and do it again :sleeping:

**Comment by lksv** [comment]
Thanks, that is great progress. Unfortunately there is still one issue when I stop and start docker again:

``` bash
lukas@luksrock:~/tmp$ sudo docker logs riak-cs
Update data permissions in case they are mounted as volumes… OK!
Starting Riak… OK!
Starting Stanchion… OK!
Starting Riak CS… OK!
Could not create admin user and retrieve credentials. Curl got response:
{}
```

That is because of [riak_cs_create_admin](https://github.com/ianbytchek/docker-riak-cs/blob/master/src/script/configure_application.sh#L116) function. When I manually set `key` and `secret` in `/etc/riak-cs/advanced.config` everything works perfectly. Should be nice to extended this function set directly `key` and `secret` from environment variables.

btw, thanks for debugging tips (I didn't know `--entrypoint` option).

**Comment by iby** [comment]
Check out the latest option. I'm a little short on time to properly test it, but it should work. See updated readme for environment vars.

**Comment by lksv** [comment]
Works perfectly! 
Thanks.
